Fixes #24: Support already installed apps in `startAppAnalysis()`
tweaselORG/cyanoacrylate pull request #25
Opened 2023-06-01 12:14 UTC by baltpeter

2023-06-02 11:53 UTC, zner0L requested changes
This is a useful addition! Thank you.

2023-06-02 16:06 UTC, baltpeter commented on src/index.ts
> +                const appMeta = await parseAppMeta(appPathMain);
I can't reproduce that. You probably have an unreleased version of appstraction installed?

2023-06-06 09:23 UTC, zner0L submitted a review, later dismissed

2023-06-06 09:23 UTC, zner0L commented on src/index.ts
> +                const appMeta = await parseAppMeta(appPathMain);
Ah, you are right! `yarn link` gets me every time.

2023-06-06 09:29 UTC, zner0L approved these changes

2023-06-06 09:29 UTC, merged