Fixes #39: Add additional metadata to HAR
tweaselORG/cyanoacrylate pull request #41
Opened 2024-04-18 13:06 UTC by baltpeter

This requires a release of https://github.com/tweaselORG/appstraction/pull/131 before it can be merged.

2024-04-27 08:41 UTC, baltpeter commented on src/index.ts
> +    };
This doesn't work if CA is starting the emulator. We'll try to communicate via adb with a device that isn't started yet (that only happens in `ensureDevice()`.

2024-05-10 09:57 UTC, baltpeter commented on src/index.ts
> +};
This should just be `Record<string, string>`.

2024-05-13 05:48 UTC, baltpeter commented on README.md
> +            "metaVersion": 1
On second thought, this should probably be a string so that we can accommodate both breaking and non-breaking changes.

2024-06-07 13:49 UTC, zner0L requested changes

2024-06-07 13:49 UTC, zner0L commented on src/index.ts
> +export type Device = {
I guess this type needs to be versioned, too, then.

2024-06-07 13:49 UTC, zner0L commented on src/index.ts
> +    options: TrafficCollectionOptions;
fi you want to be serious about versioning, we also need to pin this subtype.

2024-06-07 14:27 UTC, zner0L approved these changes

2024-06-07 14:30 UTC, zner0L approved these changes

2024-06-07 14:30 UTC, merged